export let allVinyl = [
  {
    genre: "Jazz",
    linkName: "Джаз",
    vinilName: [
      {
        id: "1",
        author: "Ray Charles",
        name: "Seven Spanish Angels And Other Hits",
        price: 10,
        year: 1989,
      },
      {
        id: "2",
        author: "Nat King Cole",
        name: "At The Sands",
        price: 25,
        year: 1966,
      },
      {
        id: "3",
        author: "Roby Weber Quartet",
        name: "Lover Of My Soul (Roby Weber Quartet Vol. 2)",
        price: 15,
        year: 1973,
      },
      {
        id: "4",
        author: "Louis Armstrong & Duke Ellington",
        name: "The Great Reunion",
        price: 20,
        year: 2016,
      },
    ],
  },
  {
    genre: "Disco",
    linkName: "Диско",
    vinilName: [
      {
        id: "5",
        author: "Robin Gibb",
        name: "Robin's Reign",
        price: 15,
        year: 1970,
      },
      { id: "6", author: "Passengers", name: "Casino", price: 10, year: 1981 },
      {
        id: "7",
        author: "Bee Gees",
        name: "Children Of The World",
        price: 5,
        year: 1976,
      },
      {
        id: "8",
        author: "ABBA",
        name: "Gold — Greatest Hits",
        price: 25,
        year: 2014,
      },
      {
        id: "9",
        author: "Savage",
        name: "Love And Rain",
        price: 15,
        year: 2020,
      },
    ],
  },
  {
    genre: "Pop",
    linkName: "Поп",
    vinilName: [
      {
        id: "10",
        author: "Rick Astley",
        name: "Whenever You Need Somebody",
        price: 35,
        year: 1988,
      },
      {
        id: "11",
        author: "Deep Purple",
        name: "Deepest Purple: The Very Best Of Deep Purple",
        price: 15,
        year: 1980,
      },
      {
        id: "12",
        author: "Frank Sinatra",
        name: "All The Way",
        price: 10,
        year: 2016,
      },
    ],
  },
  {
    genre: "Metal",
    linkName: "Метал",
    vinilName: [
      {
        id: "13",
        author: "AC/DC",
        name: "For Those About To Rock We Salute You",
        price: 15,
        year: 1981,
      },
      {
        id: "14",
        author: "Kiss",
        name: "Kiss",
        price: 15,
        year: 1974,
      },
      {
        id: "15",
        author: "Ozzy Osbourne",
        name: "Ordinary Man",
        price: 20,
        year: 2020,
      },
      {
        id: "16",
        author: "Metallica",
        name: "...And Justice For All",
        price: 25,
        year: 1988,
      },
      {
        id: "17",
        author: "Black Sabbath",
        name: "Never Say Die!",
        price: 10,
        year: 1978,
      },
    ],
  },
  {
    genre: "Rock",
    linkName: "Рок",
    vinilName: [
      { id: "18", author: "Deep Purple", name: "Burn", price: 10, year: 1974 },
      {
        id: "19",
        author: "Led Zeppelin",
        name: "In Through The Out Door",
        price: 25,
        year: 1979,
      },
      {
        id: "20",
        author: "Freddie Mercury",
        name: "Mr. Bad Guy",
        price: 30,
        year: 1985,
      },
      {
        id: "21",
        author: "Beatles",
        name: "A Hard Day's Night",
        price: 20,
        year: 1964,
      },
      {
        id: "22",
        author: "Led Zeppelin",
        name: "Led Zeppelin III",
        price: 15,
        year: 1970,
      },
    ],
  },
  {
    genre: "Classic",
    linkName: "Классика",
    vinilName: [
      {
        id: "23",
        author: "Beethoven, Berliner Philharmoniker / Lorin Maazel",
        name: "Sinfonie Nr.6 'Pastorale' 12 Kontretänze",
        price: 35,
        year: 1967,
      },
      {
        id: "24",
        author: "Schubert",
        name: "Deutsche Messe",
        price: 30,
        year: 1982,
      },
      {
        id: "25",
        author: "Richard Wagner ",
        name: "Die Meistersinger Von Nornberg - Querschnitt",
        price: 25,
        year: 1977,
      },
      {
        id: "26",
        author: "Franz Schubert",
        name: "Schubert Festival",
        price: 30,
        year: 1964,
      },
      {
        id: "27",
        author: "Johann Straus",
        name: "An Der Schonen Blauen Donau",
        price: 35,
        year: 1970,
      },
    ],
  },
  {
    genre: "Musical",
    linkName: "Мюзикл",
    vinilName: [
      {
        id: "28",
        author: "Various",
        name: "My Fair Lady",
        price: 10,
        year: 1967,
      },
      {
        id: "29",
        author: "Various",
        name: "The Sound Of Broadway",
        price: 15,
        year: 1964,
      },
    ],
  },
  {
    genre: "Electronics",
    linkName: "Электроника",
    vinilName: [
      { id: "30", author: "Yello", name: "Flag", price: 5, year: 1988 },
      { id: "31", author: "Space", name: "Deeper Zone", price: 10, year: 1980 },
      { id: "32", author: "Annie Lennox", name: "Diva", price: 20, year: 1992 },
      {
        id: "33",
        author: "Depeche Mode",
        name: "Violator",
        price: 15,
        year: 1990,
      },
    ],
  },
];
